### ISSUE TITLE
Node Gyp errors

### ISSUE THREAD

**Issue by Helixable** [plexidev/quick.db#169]
**Describe the bug**
I'm not able to install `quick.db`
**To Reproduce**
After following all the steps in the windows tutorial, run: `npm i quick.db`

**Expected behavior**
I want it to install without any errors. :|
**Screenshots**

**Desktop:**
 - OS: Windows 10
- Node: 12.18.2
- Npm: 6.14.7

**Additional context**

This is the full error: 
```
C:\Users\noahg>npm install quick.db

> integer@3.0.1 install C:\Users\noahg\node_modules\integer
> prebuild-install || npm run build-release

prebuild-install WARN install No prebuilt binaries found (target=12.18.2 runtime=node arch=x64 libc= platform=win32)

> integer@3.0.1 build-release C:\Users\noahg\node_modules\integer
> node-gyp rebuild --release


C:\Users\noahg\node_modules\integer>if not defined npm_config_node_gyp (node "C:\Users\noahg\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "C:\Users\noahg\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  integer.cpp
  win_delay_load_hook.cc
c:\users\noahg\node_modules\integer\src\integer.cpp(370): warning C4804: '-': unsafe use of type 'bool' in operation [C:\Users\noahg\node_modules\integer\build\integer.vcxproj]
C:\\Users\\noahg\\AppData\\Local\\node-gyp\\Cache\\12.18.2\\x64\\node.lib : fatal error LNK1106: invalid file or disk full: cannot seek to 0x2FCF10 [C:\Users\noahg\node_modules\integer\build\integ
er.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\noahg\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\noahg\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\noahg\node_modules\integer
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@3.0.1 build-release: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@3.0.1 build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\noahg\AppData\Roaming\npm-cache\_logs\2020-07-31T20_27_50_999Z-debug.log
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\noahg\package.json'
npm WARN noahg No description
npm WARN noahg No repository field.
npm WARN noahg No README data
npm WARN noahg No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@3.0.1 install: `prebuild-install || npm run build-release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@3.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\noahg\AppData\Roaming\npm-cache\_logs\2020-07-31T20_30_47_021Z-debug.log
```

**Comment by Mapetr** [comment]
Have you tried troubleshooting guide? I think it would resolve your problem.

**Comment by Helixable** [comment]
@Mapetr Yes I tried everything there. It still won't instll.

**Comment by Helixable** [comment]
Alright, found a solution - Completely uninstall Node.js and re-install. At the end of the installation, allow it to install necessary build tools.
