### ISSUE TITLE
SqliteError: database or disk is full

### ISSUE THREAD

**Issue by TajuModding** [plexidev/quick.db#210]
**Error**
```yaml
    at async CommandHandler.handle (/home/container/src/handler/command/commandHandler.js:148:4)
SqliteError: database or disk is full
    at Object.module.exports [as set] (/home/container/node_modules/quick.db/src/methods/set.js:11:71)
    at arbitrate (/home/container/node_modules/quick.db/src/index.js:396:27)
    at Object.set (/home/container/node_modules/quick.db/src/index.js:67:16)
    at Object.module.exports.run (/home/container/src/commands/Plugins/setwelcomeimg.js:23:8)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async CommandHandler.handle (/home/container/src/handler/command/commandHandler.js:148:4)
```
I get this error while using `quick.db` but i have 11gb of space and only used 300mb still this error. Why?

**Comment by BasToTheMax** [comment]
Maybe this can help: https://stackoverflow.com/questions/5274202/sqlite3-database-or-disk-is-full-the-database-disk-image-is-malformed
