### ISSUE TITLE
SqliteError: database or disk is full

### ISSUE THREAD

**Issue by rodycouto** [plexidev/quick.db#218]
```js
SqliteError: database or disk is full
    at Object.module.exports [as add] (/home/node/node_modules/quick.db/src/methods/add.js:37:71)
    at arbitrate (/home/node/node_modules/quick.db/src/index.js:396:27)
    at Object.add (/home/node/node_modules/quick.db/src/index.js:91:16)
    at xp (/home/node/Routes/functions/experience.js:16:8)
    at Client.<anonymous> (/home/node/src/events/messageCreate.js:38:13)
    at Client.emit (node:events:394:28)
    at Client.emit (node:domain:475:12)
    at MessageCreateAction.handle (/home/node/node_modules/discord.js/src/client/actions/MessageCreate.js:23:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/node/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/node/node_modules/discord.js/src/client/websocket/WebSocketManager.js:350:31)
```

1.228KB - If it's local, why database got full?

**Comment by Nigelrex** [comment]
How big is your `.sqlite` file, and if it is not big that 50MB check your disk

**Comment by KK-Designs** [comment]
@Nigelrex he said it was `1.228KB`
