### ISSUE TITLE
Bot wont start ERR_DLOPEN_FAILED

### ISSUE THREAD

**Issue by tayron1** [plexidev/quick.db#252]
E:\Dev\JS\Eventy\node_modules\bindings\bindings.js:121
        throw e;
        ^

Error: The module '\\?\E:\Dev\JS\Eventy\node_modules\better-sqlite3\build\Release\better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 108. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Module._extensions..node (node:internal/modules/cjs/loader:1233:18)
    at Module.load (node:internal/modules/cjs/loader:1027:32)
    at Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1051:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at bindings (E:\Dev\JS\Eventy\node_modules\bindings\bindings.js:112:48)
    at new Database (E:\Dev\JS\Eventy\node_modules\better-sqlite3\lib\database.js:48:64)
    at Database (E:\Dev\JS\Eventy\node_modules\better-sqlite3\lib\database.js:11:10)
    at new SqliteDriver (E:\Dev\JS\Eventy\node_modules\quick.db\out\drivers\SqliteDriver.js:8:25)
    at new QuickDB (E:\Dev\JS\Eventy\node_modules\quick.db\out\index.js:17:28) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.10.0

**Comment by lorencerri** [comment]
It looks like you installed quick.db, then updated your version of node. Since it was compiled against that version, you would need to install quick.db again.

**Comment by lorencerri** [comment]
I'm going to close this, although if it's still an issue feel free to re-open it or send a message in our Discord server!
