### ISSUE TITLE
invalid ELF header

### ISSUE THREAD

**Issue by makarasty** [plexidev/quick.db#255]
```
/home/container/node_modules/bindings/bindings.js:121
        throw e;
        ^
Error: /home/container/node_modules/better-sqlite3/build/Release/better_sqlite3.node: invalid ELF header
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1179:18)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/home/container/node_modules/bindings/bindings.js:112:48)
    at new Database (/home/container/node_modules/better-sqlite3/lib/database.js:48:64)
    at Database (/home/container/node_modules/better-sqlite3/lib/database.js:11:10)
    at new SqliteDriver (/home/container/node_modules/quick.db/out/drivers/SqliteDriver.js:8:25)
    at new QuickDB (/home/container/node_modules/quick.db/out/index.js:17:28) {
  code: 'ERR_DLOPEN_FAILED'
}
Node.js v17.3.0
```

I have this error on the hosting

**Comment by pendragons-code** [comment]
This usually happens if you are using a different architecture (arm, x86) to host the project. To get around this, delete the node_modules folder and run `npm i`. This will allow you to install all the needed modules in the package.json folder.

This is unlikely a major issue so once you do solve this problem, please close it.

**Comment by Zelak312** [comment]
As @pendragons-code said. This is mostly likely the issue.

I wanted to add that node_modules should never be transfered or downloaded to an other machine as It is not recommended to do.

It will also make sure this issue doesn't happen again since you will have to reinstall the dependencies on the target system which will compile the bindings correctly for the current architecture

**Comment by makarasty** [comment]
> As @pendragons-code said. This is mostly likely the issue.
> 
> I wanted to add that node_modules should never be transfered or downloaded to an other machine as It is not recommended to do.
> 
> It will also make sure this issue doesn't happen again since you will have to reinstall the dependencies on the target system which will compile the bindings correctly for the current architecture

```
/home/container/node_modules/bindings/bindings.js:135
  throw err;
  ^
Error: Could not locate the bindings file. Tried:
 → /home/container/node_modules/better-sqlite3/build/better_sqlite3.node
 → /home/container/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
 → /home/container/node_modules/better-sqlite3/build/Release/better_sqlite3.node
 → /home/container/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
 → /home/container/node_modules/better-sqlite3/Debug/better_sqlite3.node
 → /home/container/node_modules/better-sqlite3/out/Release/better_sqlite3.node
 → /home/container/node_modules/better-sqlite3/Release/better_sqlite3.node
 → /home/container/node_modules/better-sqlite3/build/default/better_sqlite3.node
 → /home/container/node_modules/better-sqlite3/compiled/17.3.0/linux/x64/better_sqlite3.node
 → /home/container/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
 → /home/container/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
 → /home/container/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
 → /home/container/node_modules/better-sqlite3/lib/binding/node-v102-linux-x64/better_sqlite3.node
    at bindings (/home/container/node_modules/bindings/bindings.js:126:9)
    at new Database (/home/container/node_modules/better-sqlite3/lib/database.js:48:64)
    at Database (/home/container/node_modules/better-sqlite3/lib/database.js:11:10)
    at new SqliteDriver (/home/container/node_modules/quick.db/out/drivers/SqliteDriver.js:8:25)
    at new QuickDB (/home/container/node_modules/quick.db/out/index.js:17:28)
    at new Bot (/home/container/structures/client.js:26:13)
    at Object.<anonymous> (/home/container/index.js:3:16)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32) {
  tries: [
    '/home/container/node_modules/better-sqlite3/build/better_sqlite3.node',
    '/home/container/node_modules/better-sqlite3/build/Debug/better_sqlite3.node',
    '/home/container/node_modules/better-sqlite3/build/Release/better_sqlite3.node',
    '/home/container/node_modules/better-sqlite3/out/Debug/better_sqlite3.node',
    '/home/container/node_modules/better-sqlite3/Debug/better_sqlite3.node',
    '/home/container/node_modules/better-sqlite3/out/Release/better_sqlite3.node',
    '/home/container/node_modules/better-sqlite3/Release/better_sqlite3.node',
    '/home/container/node_modules/better-sqlite3/build/default/better_sqlite3.node',
    '/home/container/node_modules/better-sqlite3/compiled/17.3.0/linux/x64/better_sqlite3.node',
    '/home/container/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node',
    '/home/container/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node',
    '/home/container/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node',
    '/home/container/node_modules/better-sqlite3/lib/binding/node-v102-linux-x64/better_sqlite3.node'
  ]
}
Node.js v17.3.0
```

If I don't transfer files from my PC I will get this error

**Comment by makarasty** [comment]
Well I solved this problem by using the correct version on github and compiling the package manually
[link](https://github.com/WiseLibs/better-sqlite3/releases)
