### ISSUE TITLE
SyntaxError: Unexpected token '?'  on ubuntu

### ISSUE THREAD

**Issue by tzwel** [plexidev/quick.db#257]
**Describe the bug**
When running the code in node:

```
        options.table ??= "json";
                       ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Node version: v18.12.0
 - Version ^9.0.6

**Comment by Zelak312** [comment]
You have ab old version of nodejs. You said you have 18.12.x which should ve totally false because null the coalescing operator (??) wat added in nodejs version 14.0.0 as seen here <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator>

Update your nodejs version
